table FlowAux_FirstQualifiedCandidate
	lineageTag: 0dfba99d-72ba-411f-99cc-5056f2179f5a

	column First_Request_ID
		dataType: string
		lineageTag: 9246a409-c83d-41eb-bdb6-bfd8188f2da3
		summarizeBy: none
		sourceColumn: First_Request_ID

		annotation SummarizationSetBy = Automatic

	column '1st Qualified Candidate Flag'
		dataType: int64
		formatString: 0
		lineageTag: 9c8b3560-fce9-49ed-8883-4a75bf7716bf
		summarizeBy: sum
		sourceColumn: 1st Qualified Candidate Flag

		annotation SummarizationSetBy = Automatic

	column '1ts Candidate Submitted Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b6cd66bc-4936-4fe4-8af4-dc9c1abab4f9
		summarizeBy: none
		sourceColumn: 1ts Candidate Submitted Date

		annotation SummarizationSetBy = Automatic

	partition FlowAux_FirstQualifiedCandidate = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(),
				    Workspaces = Source{[Id = "Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId="8a87c474-d74a-479b-8616-3bbb0e4f223d"]}[Data],
				    Dataflow = Workspace{[dataflowId="22bc9ade-d2a9-44e0-bfe4-2f00ff94f2ed"]}[Data],
				    Entity = Dataflow{[entity="FlowAuxMergeRequestsCandidates"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Entity,{{"Candidate Offer Date", "Candidate Offer Extended Date"}, {"Candidate Qualified Date", "Candidate HM Qualified Date"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Request_ID"}, FlowAux_Merge_Request_Dates_and_IDs, {"Request_ID"}, "FlowzzAuxMerge_Request_Dates_and_IDs", JoinKind.LeftOuter),
				    #"Expanded FlowzzAuxMerge_Request_Dates_and_IDs" = Table.ExpandTableColumn(#"Merged Queries", "FlowzzAuxMerge_Request_Dates_and_IDs", {"Request_ID", "Currency Exchange Rate to USD", "Rate Card Rate RT", "Request Filled Date", "Request Submitted Date", "Request Desired Start Date", "Procurement_Type_KEY", "Request Released Date", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}, {"Request_ID.1", "Currency Exchange Rate to USD", "Rate Card Rate RT", "Request Filled Date", "Request Submitted Date", "Request Desired Start Date", "Procurement_Type_KEY", "Request Released Date", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded FlowzzAuxMerge_Request_Dates_and_IDs", each [Request_ID.1] <> null),
				    NewColumn1stQualifiedCandidateFlag = Table.AddColumn(#"Filtered Rows", "1st Qualified Candidate Flag", each if ([Candidate Hired Date] = null or [Candidate MSP Qualified Date] = null or [Candidate Offer Accepted Date] = null or [Candidate Offer Extended Date]= null or [Candidate On boarded Date] = null or [Candidate HM Qualified Date]= null or [Candidate Interview Requested Date] = null or [Candidate Interview Scheduled Date] = null or [Candidate Interview Completed Date] = null or ([Candidate Interview Rating] = null and [Candidate Interview Rating] <> 0) ) then 1 else 0, Int64.Type),
				    #"Filtered Rows1" = Table.SelectRows(NewColumn1stQualifiedCandidateFlag, each ([1st Qualified Candidate Flag] = 1)),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows1", {"Request_ID", "1st Qualified Candidate Flag"}, {{"1ts Candidate Submitted Date", each List.Min([Candidate Submitted Date]), type nullable datetime}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Grouped Rows",{{"Request_ID", "First_Request_ID"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

