table FlowPreFactRequestCandidate
	lineageTag: 5be21951-d4fd-4cd3-a173-f276efa2a71d

	column Request_ID
		dataType: string
		lineageTag: 8ae4aaec-d9be-449d-b046-efd5bac6136b
		summarizeBy: none
		sourceColumn: Request_ID

		annotation SummarizationSetBy = Automatic

	column 'Candidate Is Self Sourced'
		dataType: string
		lineageTag: 61fb9389-ec1f-4698-88f5-8d3e34f45fbe
		summarizeBy: none
		sourceColumn: Candidate Is Self Sourced

		annotation SummarizationSetBy = Automatic

	column 'Resource ID'
		dataType: string
		lineageTag: c960b52e-a1e5-4ddb-8da0-834ecf72b488
		summarizeBy: none
		sourceColumn: Resource ID

		annotation SummarizationSetBy = Automatic

	column ClientNameInternal
		dataType: string
		lineageTag: df2a6cd8-348c-4924-9cfe-7cd122f4b8a5
		summarizeBy: none
		sourceColumn: ClientNameInternal

		annotation SummarizationSetBy = Automatic

	column Candidate_ID
		dataType: string
		lineageTag: 79da7c48-8aef-43db-8364-d96432782dee
		summarizeBy: none
		sourceColumn: Candidate_ID

		annotation SummarizationSetBy = Automatic

	column 'Candidate Interview Rating'
		dataType: double
		lineageTag: c2ff515a-b256-44a5-b024-d7c399c01693
		summarizeBy: sum
		sourceColumn: Candidate Interview Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Candidate Pay Rate RT'
		dataType: double
		lineageTag: 44f883cc-d4fa-4b6f-8071-db573f381974
		summarizeBy: sum
		sourceColumn: Candidate Pay Rate RT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Candidate Bill Rate RT'
		dataType: double
		lineageTag: b8fa239c-eb6f-45d6-b8e3-4eefdcef64f9
		summarizeBy: sum
		sourceColumn: Candidate Bill Rate RT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UDF1_KEY
		dataType: int64
		formatString: 0
		lineageTag: f79c72e6-e6c7-4ac9-8e0d-4c29b3e5587c
		summarizeBy: sum
		sourceColumn: UDF1_KEY

		annotation SummarizationSetBy = Automatic

	column UDF2_KEY
		dataType: int64
		formatString: 0
		lineageTag: 1eecc795-25cf-4508-8039-fb25c62f4509
		summarizeBy: sum
		sourceColumn: UDF2_KEY

		annotation SummarizationSetBy = Automatic

	column UDF4_KEY
		dataType: int64
		formatString: 0
		lineageTag: aac52df2-5539-414e-9733-672cbcb35b7a
		summarizeBy: sum
		sourceColumn: UDF4_KEY

		annotation SummarizationSetBy = Automatic

	column 'Supplier Released Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 90e914f3-c7e4-4323-96c5-35bb5ae8a8db
		summarizeBy: none
		sourceColumn: Supplier Released Date

		annotation SummarizationSetBy = Automatic

	column UDF5_KEY
		dataType: int64
		formatString: 0
		lineageTag: 44b58a64-bfa4-4b67-9cae-427999e2c9c9
		summarizeBy: sum
		sourceColumn: UDF5_KEY

		annotation SummarizationSetBy = Automatic

	column 'Data Refreshed Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a84a1fd8-b54a-4127-b456-28317da15ce9
		summarizeBy: none
		sourceColumn: Data Refreshed Date

		annotation SummarizationSetBy = Automatic

	column Resource_Type_KEY
		dataType: int64
		formatString: 0
		lineageTag: 870f961e-8e68-4be8-87df-a6a2ecd2e7c2
		summarizeBy: sum
		sourceColumn: Resource_Type_KEY

		annotation SummarizationSetBy = Automatic

	column UDF3_KEY
		dataType: int64
		formatString: 0
		lineageTag: 8e4b95b0-db10-4361-ba9e-ca756fbd141a
		summarizeBy: sum
		sourceColumn: UDF3_KEY

		annotation SummarizationSetBy = Automatic

	column Client_Name_KEY
		dataType: int64
		formatString: 0
		lineageTag: ab642ee1-91a3-4a9a-a967-9dae47e08dae
		summarizeBy: sum
		sourceColumn: Client_Name_KEY

		annotation SummarizationSetBy = Automatic

	column 'Candidate Interview Requested Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: f6d5c4ae-e911-428b-8ad6-2a17bf04ad86
		summarizeBy: none
		sourceColumn: Candidate Interview Requested Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate Interview Scheduled Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 88bb0117-751f-4a2f-9efe-5efff3e6e6c6
		summarizeBy: none
		sourceColumn: Candidate Interview Scheduled Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate Hired Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a133042e-f00a-4604-bb3c-91af0ed4386e
		summarizeBy: none
		sourceColumn: Candidate Hired Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate On boarded Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: d9101501-1e2d-45cb-86ba-18787c52e937
		summarizeBy: none
		sourceColumn: Candidate On boarded Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate Offer Accepted Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b2067bf7-75c6-4417-995f-5ff33885f2ad
		summarizeBy: none
		sourceColumn: Candidate Offer Accepted Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate Offer Extended Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 8f52f2f8-1186-4a90-9093-94abee18c25d
		summarizeBy: none
		sourceColumn: Candidate Offer Extended Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate MSP Qualified Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6edc2545-7bde-4a58-a1ba-e2207f7b4eea
		summarizeBy: none
		sourceColumn: Candidate MSP Qualified Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate HM Disqualified Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b54afd06-5fef-4618-931e-c3e78e1932af
		summarizeBy: none
		sourceColumn: Candidate HM Disqualified Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate HM Qualified Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 187e5c64-2ecd-4560-a97d-e88e50746969
		summarizeBy: none
		sourceColumn: Candidate HM Qualified Date

		annotation SummarizationSetBy = Automatic

	column 'Candidate Submitted Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 41876092-87ff-488b-a5b0-ae934e24e13d
		summarizeBy: none
		sourceColumn: Candidate Submitted Date

		annotation SummarizationSetBy = Automatic

	column Candidate_Internal_Status_KEY
		dataType: int64
		formatString: 0
		lineageTag: 3d4fcf0c-0802-4b2d-a574-13c859bdb506
		summarizeBy: sum
		sourceColumn: Candidate_Internal_Status_KEY

		annotation SummarizationSetBy = Automatic

	column 'Candidate Interview Completed Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 601a36c8-9e73-4d6d-b6fa-e5ddb8f394d1
		summarizeBy: none
		sourceColumn: Candidate Interview Completed Date

		annotation SummarizationSetBy = Automatic

	column Supplier_KEY
		dataType: int64
		formatString: 0
		lineageTag: 124c30ff-3a2f-442b-9155-371ce588c5fc
		summarizeBy: sum
		sourceColumn: Supplier_KEY

		annotation SummarizationSetBy = Automatic

	column 'Request_ID.1'
		dataType: string
		lineageTag: 3acdd466-3800-4048-9993-7c7daf2f95a7
		summarizeBy: none
		sourceColumn: Request_ID.1

		annotation SummarizationSetBy = Automatic

	column 'Currency Exchange Rate to USD'
		dataType: double
		lineageTag: eee0a831-08eb-40f5-93fa-51b048adef9a
		summarizeBy: sum
		sourceColumn: Currency Exchange Rate to USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Rate Card Rate RT'
		dataType: double
		lineageTag: 7791a2d1-5a23-4ca8-8962-cd054605c5ee
		summarizeBy: sum
		sourceColumn: Rate Card Rate RT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Request Filled Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 84855da3-ec63-4030-9521-91fa8c83878b
		summarizeBy: none
		sourceColumn: Request Filled Date

		annotation SummarizationSetBy = Automatic

	column 'Request Submitted Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7480eb59-4598-4e8b-9f0e-c985d7f15585
		summarizeBy: none
		sourceColumn: Request Submitted Date

		annotation SummarizationSetBy = Automatic

	column 'Request Desired Start Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b1463ee-cf37-4ec6-9e60-4db8d686bc83
		summarizeBy: none
		sourceColumn: Request Desired Start Date

		annotation SummarizationSetBy = Automatic

	column Procurement_Type_KEY
		dataType: int64
		formatString: 0
		lineageTag: 697bbba7-8f51-4764-95c6-a76a3e11e874
		summarizeBy: sum
		sourceColumn: Procurement_Type_KEY

		annotation SummarizationSetBy = Automatic

	column 'Request Released Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: b8c55c2e-1bcb-462b-8a85-1fd8a9a4c9b4
		summarizeBy: none
		sourceColumn: Request Released Date

		annotation SummarizationSetBy = Automatic

	column Rate_Card_Category_1_KEY
		dataType: int64
		formatString: 0
		lineageTag: f550ec55-a691-4965-bce1-a74b62669daa
		summarizeBy: sum
		sourceColumn: Rate_Card_Category_1_KEY

		annotation SummarizationSetBy = Automatic

	column 'Request Approved Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 610d1ca9-ffb6-49e8-afc0-b3ca87226311
		summarizeBy: none
		sourceColumn: Request Approved Date

		annotation SummarizationSetBy = Automatic

	column Business_Unit_KEY
		dataType: int64
		formatString: 0
		lineageTag: 59437d57-9351-47ee-8367-419efb6537dc
		summarizeBy: sum
		sourceColumn: Business_Unit_KEY

		annotation SummarizationSetBy = Automatic

	column Currency_KEY
		dataType: int64
		formatString: 0
		lineageTag: 6d5d0ceb-61f4-4209-a81e-a5482e5e9dec
		summarizeBy: sum
		sourceColumn: Currency_KEY

		annotation SummarizationSetBy = Automatic

	column Work_Location_KEY
		dataType: int64
		formatString: 0
		lineageTag: 1c91c695-f7dc-45fa-9acf-13c349a23dd1
		summarizeBy: sum
		sourceColumn: Work_Location_KEY

		annotation SummarizationSetBy = Automatic

	column Job_Title_KEY
		dataType: int64
		formatString: 0
		lineageTag: 6dd4571c-bc9f-4644-b306-4eb5024b5357
		summarizeBy: sum
		sourceColumn: Job_Title_KEY

		annotation SummarizationSetBy = Automatic

	column Rate_Card_Category_2_KEY
		dataType: int64
		formatString: 0
		lineageTag: 9c053b0f-4c4b-46d8-a982-9e521cd42143
		summarizeBy: sum
		sourceColumn: Rate_Card_Category_2_KEY

		annotation SummarizationSetBy = Automatic

	column Labor_Category_KEY
		dataType: int64
		formatString: 0
		lineageTag: e3b275e4-01d8-40ff-9971-b6948b39b304
		summarizeBy: sum
		sourceColumn: Labor_Category_KEY

		annotation SummarizationSetBy = Automatic

	column Job_Class_KEY
		dataType: int64
		formatString: 0
		lineageTag: 5fa19223-ab30-44a0-8255-d48f5a44a750
		summarizeBy: sum
		sourceColumn: Job_Class_KEY

		annotation SummarizationSetBy = Automatic

	column Hiring_Manager_KEY
		dataType: int64
		formatString: 0
		lineageTag: 3a3cf6a7-e4ca-4fb9-8acc-6fe060b47f67
		summarizeBy: sum
		sourceColumn: Hiring_Manager_KEY

		annotation SummarizationSetBy = Automatic

	column Cost_Center_KEY
		dataType: int64
		formatString: 0
		lineageTag: 131108e4-224b-471d-a92e-4a85d1340da9
		summarizeBy: sum
		sourceColumn: Cost_Center_KEY

		annotation SummarizationSetBy = Automatic

	column 'Cycle Time From Submitted To MSP Qualified (Cal Days)'
		dataType: double
		lineageTag: 56a02466-df23-4f8b-beed-a409d42056c2
		summarizeBy: sum
		sourceColumn: Cycle Time From Submitted To MSP Qualified (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Submitted To HM Qualified (Cal Days)'
		dataType: double
		lineageTag: 01aa7024-3198-48d5-a879-00d3924b2291
		summarizeBy: sum
		sourceColumn: Cycle Time From Submitted To HM Qualified (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Submitted To Offer Extended (Cal Days)'
		dataType: double
		lineageTag: f13443fa-4618-461b-9cfb-90ffa166aa9c
		summarizeBy: sum
		sourceColumn: Cycle Time From Submitted To Offer Extended (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Submitted To Interview Scheduled (Cal Days)'
		dataType: double
		lineageTag: 14d5c8fe-d026-4239-b8a5-8aeafda016f7
		summarizeBy: sum
		sourceColumn: Cycle Time From Submitted To Interview Scheduled (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From MSP Qualified to HM Qualified (Cal Days)'
		dataType: double
		lineageTag: 2e5de30a-6e40-4d65-9dd8-23ce4e47b07b
		summarizeBy: sum
		sourceColumn: Cycle Time From MSP Qualified to HM Qualified (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From HM Qualified to Offer Extended (Cal Days)'
		dataType: double
		lineageTag: afe71f64-f077-476c-9d03-12ecaa60a2e1
		summarizeBy: sum
		sourceColumn: Cycle Time From HM Qualified to Offer Extended (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From MSP Qualified to Offer Extended (Cal Days)'
		dataType: double
		lineageTag: 0a4495e1-c13e-4299-838e-7a7739314c3e
		summarizeBy: sum
		sourceColumn: Cycle Time From MSP Qualified to Offer Extended (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Offer Extended to Offer Accepted (Cal Days)'
		dataType: double
		lineageTag: 51583805-93ac-447b-abe0-70fa0f70ef94
		summarizeBy: sum
		sourceColumn: Cycle Time From Offer Extended to Offer Accepted (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Offer Accepted To Onboard (Cal Days)'
		dataType: double
		lineageTag: 0e1f5bde-0cf6-439b-bfd5-ae229ce20b73
		summarizeBy: sum
		sourceColumn: Cycle Time From Offer Accepted To Onboard (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Offer Accepted to Hired (Cal Days)'
		dataType: double
		lineageTag: dea792b7-d50b-45ec-9fe1-9ecba67f9a1c
		summarizeBy: sum
		sourceColumn: Cycle Time From Offer Accepted to Hired (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Submitted To Hired (Cal Days)'
		dataType: double
		lineageTag: 169d58cf-3bd5-4a7e-aa90-e17759783754
		summarizeBy: sum
		sourceColumn: Cycle Time From Submitted To Hired (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Submitted To Onboard (Cal Days)'
		dataType: double
		lineageTag: bb9adafa-bb1c-4e79-947a-f62101737263
		summarizeBy: sum
		sourceColumn: Cycle Time From Submitted To Onboard (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cycle Time From Request Received To Submitted (Cal Days)'
		dataType: double
		lineageTag: c9d19e14-2633-4c78-a703-c44359815704
		summarizeBy: sum
		sourceColumn: Cycle Time From Request Received To Submitted (Cal Days)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Candidate A/B/E Request Bill Rate'
		dataType: string
		lineageTag: fec5e245-24f3-4f1d-8e8e-6a0dcf9ab71d
		summarizeBy: none
		sourceColumn: Candidate A/B/E Request Bill Rate

		annotation SummarizationSetBy = Automatic

	column 'Candidate Markup %'
		dataType: double
		lineageTag: 64c3eb5d-e567-4e04-b1d1-7f740cdabe26
		summarizeBy: sum
		sourceColumn: Candidate Markup %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Candidate Bill Rate RT USD'
		dataType: double
		lineageTag: 475841a8-d7b6-4faf-a3c6-69c4f5e00857
		summarizeBy: sum
		sourceColumn: Candidate Bill Rate RT USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Candidate Pay Rate RT USD'
		dataType: double
		lineageTag: 97814e04-a1be-4ad1-88b4-d2b5b06bceff
		summarizeBy: sum
		sourceColumn: Candidate Pay Rate RT USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Qualified Candidate Flag'
		dataType: int64
		formatString: 0
		lineageTag: d343e891-6abe-4c31-ad0f-9a192c130cfd
		summarizeBy: sum
		sourceColumn: Qualified Candidate Flag

		annotation SummarizationSetBy = Automatic

	column 'Median Submitted Bill Rates'
		dataType: double
		lineageTag: 5038ff46-78c5-476e-ab51-96620bbb6ae7
		summarizeBy: sum
		sourceColumn: Median Submitted Bill Rates

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Median Submitted Bill Rates USD'
		dataType: double
		lineageTag: f70902a6-90c4-4105-a5c3-e0175c613ec1
		summarizeBy: sum
		sourceColumn: Median Submitted Bill Rates USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '1st Qualified Candidate Flag'
		dataType: int64
		formatString: 0
		lineageTag: f4e7d650-f3dd-470d-a831-08756519a7f5
		summarizeBy: sum
		sourceColumn: 1st Qualified Candidate Flag

		annotation SummarizationSetBy = Automatic

	column 'Candidate A/B/E Median Submitted Rate'
		dataType: string
		lineageTag: fe60e8af-282e-4fa0-8bde-a32c278e0daf
		summarizeBy: none
		sourceColumn: Candidate A/B/E Median Submitted Rate

		annotation SummarizationSetBy = Automatic

	column 'Qualified Candidate Response (In Hours)'
		dataType: double
		lineageTag: d5aa11cc-346e-4696-ad19-e47b359f7dad
		summarizeBy: sum
		sourceColumn: Qualified Candidate Response (In Hours)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FlowPreFactRequestCandidate = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(),
				    Workspaces = Source{[Id = "Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId="8a87c474-d74a-479b-8616-3bbb0e4f223d"]}[Data],
				    Dataflow = Workspace{[dataflowId="22bc9ade-d2a9-44e0-bfe4-2f00ff94f2ed"]}[Data],
				    Entity = Dataflow{[entity="FlowAuxMergeRequestsCandidates"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Entity,{{"Candidate Offer Date", "Candidate Offer Extended Date"}, {"Candidate Qualified Date", "Candidate HM Qualified Date"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Request_ID"}, FlowAux_Merge_Request_Dates_and_IDs, {"Request_ID"}, "FlowzzAuxMerge_Request_Dates_and_IDs", JoinKind.LeftOuter),
				    #"Expanded FlowzzAuxMerge_Request_Dates_and_IDs" = Table.ExpandTableColumn(#"Merged Queries", "FlowzzAuxMerge_Request_Dates_and_IDs", {"Request_ID", "Currency Exchange Rate to USD", "Rate Card Rate RT", "Request Filled Date", "Request Submitted Date", "Request Desired Start Date", "Procurement_Type_KEY", "Request Released Date", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}, {"Request_ID.1", "Currency Exchange Rate to USD", "Rate Card Rate RT", "Request Filled Date", "Request Submitted Date", "Request Desired Start Date", "Procurement_Type_KEY", "Request Released Date", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded FlowzzAuxMerge_Request_Dates_and_IDs", each [Request_ID.1] <> null),
				  NewColumnCycleTimeFromSubmittedToMSPQualifiedCalDays = Table.AddColumn(#"Filtered Rows", "Cycle Time From Submitted To MSP Qualified (Cal Days)", each Duration.TotalDays([Candidate MSP Qualified Date] - [Candidate Submitted Date]), type number),
				    NewColumnCycleTimeFromSubmittedToHMQualifiedCalDays = Table.AddColumn(NewColumnCycleTimeFromSubmittedToMSPQualifiedCalDays, "Cycle Time From Submitted To HM Qualified (Cal Days)", each Duration.TotalDays([Candidate HM Qualified Date] - [Candidate Submitted Date]), type number),
				    NewColumnCycleTimeFromSubmittedToOfferExtendedCalDays = Table.AddColumn(NewColumnCycleTimeFromSubmittedToHMQualifiedCalDays, "Cycle Time From Submitted To Offer Extended (Cal Days)", each Duration.TotalDays([Candidate Offer Extended Date] - [Candidate Submitted Date]), type number),
				    NewColumnCycleTimeFromSubmittedToInterviewScheduledCalDays = Table.AddColumn(NewColumnCycleTimeFromSubmittedToOfferExtendedCalDays, "Cycle Time From Submitted To Interview Scheduled (Cal Days)", each Duration.TotalDays([Candidate Interview Scheduled Date] - [Candidate Submitted Date]), type number),
				    NewColumnCycleTimeFromMSPQualifiedToHMQualifiedCalDays = Table.AddColumn(NewColumnCycleTimeFromSubmittedToInterviewScheduledCalDays, "Cycle Time From MSP Qualified to HM Qualified (Cal Days)", each Duration.TotalDays([Candidate MSP Qualified Date] - [Candidate HM Qualified Date]), type number),
				    NewColumnCycleTimeFromHMQualifiedToOfferExtendedCalDays = Table.AddColumn(NewColumnCycleTimeFromMSPQualifiedToHMQualifiedCalDays, "Cycle Time From HM Qualified to Offer Extended (Cal Days)", each Duration.TotalDays([Candidate Offer Extended Date] - [Candidate HM Qualified Date]), type number),
				    NewColumnCycleTimeFromMSPQualifiedToOfferExtendedCalDays = Table.AddColumn(NewColumnCycleTimeFromHMQualifiedToOfferExtendedCalDays, "Cycle Time From MSP Qualified to Offer Extended (Cal Days)", each Duration.TotalDays([Candidate Offer Extended Date] - [Candidate MSP Qualified Date]), type number),
				    NewColumnCycleTimeFromOfferExtendedToOfferAcceptedCalDays = Table.AddColumn(NewColumnCycleTimeFromMSPQualifiedToOfferExtendedCalDays, "Cycle Time From Offer Extended to Offer Accepted (Cal Days)", each Duration.TotalDays([Candidate Offer Accepted Date] - [Candidate Offer Extended Date]), type number),
				    NewColumnCycleTimeFromOfferAcceptedToOnboardCalDays = Table.AddColumn(NewColumnCycleTimeFromOfferExtendedToOfferAcceptedCalDays, "Cycle Time From Offer Accepted To Onboard (Cal Days)", each Duration.TotalDays([Candidate On boarded Date] - [Candidate Offer Accepted Date]), type number),
				    NewColumnCycleTimeFromOfferAcceptedToHiredCalDays = Table.AddColumn(NewColumnCycleTimeFromOfferAcceptedToOnboardCalDays, "Cycle Time From Offer Accepted to Hired (Cal Days)", each Duration.TotalDays([Candidate Hired Date] - [Candidate Offer Accepted Date]), type number),
				    NewColumnCycleTimeFromSubmittedToHiredCalDays = Table.AddColumn(NewColumnCycleTimeFromOfferAcceptedToHiredCalDays, "Cycle Time From Submitted To Hired (Cal Days)", each Duration.TotalDays([Candidate Hired Date] - [Candidate Submitted Date]), type number),
				    NewColumnCycleTimeFromSubmittedToOnboardCalDays = Table.AddColumn(NewColumnCycleTimeFromSubmittedToHiredCalDays, "Cycle Time From Submitted To Onboard (Cal Days)", each Duration.TotalDays([Candidate On boarded Date] - [Candidate Submitted Date]), type number),
				    NewColumnCycleTimeFromRequestReceivedToSubmittedCalDays = Table.AddColumn(NewColumnCycleTimeFromSubmittedToOnboardCalDays, "Cycle Time From Request Received To Submitted (Cal Days)", each Duration.TotalDays([Candidate Submitted Date] - [Supplier Released Date]), type number),
				    NewColumnCandidateABERequestBillRate = Table.AddColumn(NewColumnCycleTimeFromRequestReceivedToSubmittedCalDays, "Candidate A/B/E Request Bill Rate", each if [Candidate Bill Rate RT] = null then "N/A (Missing Candidate Bill Rate)" else if [Rate Card Rate RT] = null then "N/A (Missing Request Bill Rate)" else if [Candidate Bill Rate RT] < [Rate Card Rate RT] then "Below" else if [Candidate Bill Rate RT] = [Rate Card Rate RT] then "Equal" else if [Candidate Bill Rate RT] > [Rate Card Rate RT] then "Above" else "N/A (Unknown Error)", type text),
				    NewColumnCandidateMarkupPercent = Table.AddColumn(NewColumnCandidateABERequestBillRate, "Candidate Markup %", each if [Candidate Pay Rate RT] = 0 then null else (([Candidate Bill Rate RT] - [Candidate Pay Rate RT]) / [Candidate Pay Rate RT]), type number),
				    NewColumnCandidateBillRateRTUSD = Table.AddColumn(NewColumnCandidateMarkupPercent, "Candidate Bill Rate RT USD", each [Candidate Bill Rate RT] * [Currency Exchange Rate to USD], type number),
				    NewColumnCandidatePayRateRTUSD = Table.AddColumn(NewColumnCandidateBillRateRTUSD, "Candidate Pay Rate RT USD", each [Candidate Pay Rate RT] * [Currency Exchange Rate to USD], type number),
				    RemovedDuplicates = Table.Distinct(NewColumnCandidatePayRateRTUSD),
				    NewColumnQualifiedCandidateFlag = Table.AddColumn(RemovedDuplicates, "Qualified Candidate Flag", each if ([Candidate Hired Date] = null or [Candidate MSP Qualified Date] = null or [Candidate Offer Accepted Date] = null or [Candidate Offer Extended Date]= null or [Candidate On boarded Date] = null or [Candidate HM Qualified Date]= null or [Candidate Interview Requested Date] = null or [Candidate Interview Scheduled Date] = null or [Candidate Interview Completed Date] = null or ([Candidate Interview Rating] = null and [Candidate Interview Rating] <> 0) ) then 1 else 0, Int64.Type),
				    #"Merged Queries1" = Table.NestedJoin(NewColumnQualifiedCandidateFlag, {"Request_ID"}, FlowAux_Median_Submitted_Bill_Rates, {"Request_ID"}, "FlowAuxMedian_Submitted_Bill_Rates", JoinKind.LeftOuter),
				    #"Expanded FlowAuxMedian_Submitted_Bill_Rates" = Table.ExpandTableColumn(#"Merged Queries1", "FlowAuxMedian_Submitted_Bill_Rates", {"Median Submitted Bill Rates", "Median Submitted Bill Rates USD"}, {"Median Submitted Bill Rates", "Median Submitted Bill Rates USD"}),
				    #"Merged Queries2" = Table.NestedJoin(#"Expanded FlowAuxMedian_Submitted_Bill_Rates", {"Request_ID"}, FlowAux_FirstQualifiedCandidate, {"First_Request_ID"}, "FlowAuxFirst_QualifiedCandidate", JoinKind.LeftOuter),
				    #"Expanded FlowAuxFirst_QualifiedCandidate" = Table.ExpandTableColumn(#"Merged Queries2", "FlowAuxFirst_QualifiedCandidate", {"1st Qualified Candidate Flag"}, {"1st Qualified Candidate Flag"}),
				    NewColumnCandidateABEMedianSubmittedRate = Table.AddColumn(#"Expanded FlowAuxFirst_QualifiedCandidate", "Candidate A/B/E Median Submitted Rate", each if [Candidate Bill Rate RT] < [Median Submitted Bill Rates] then "Below" else if [Candidate Bill Rate RT] = [Median Submitted Bill Rates] then "Equal" else if [Candidate Bill Rate RT] >  [Median Submitted Bill Rates] then "Above" else "N/A", type text),
				    NewColumnQualifiedCandidateResponseInHours = Table.AddColumn(NewColumnCandidateABEMedianSubmittedRate, "Qualified Candidate Response (In Hours)",  each if [Qualified Candidate Flag] = null then null else  if [Qualified Candidate Flag] = 1 then Duration.TotalHours([Candidate Submitted Date] - [Supplier Released Date]) else null , type number)
				in
				    NewColumnQualifiedCandidateResponseInHours

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

