table FlowAux_Candidates_Submitted_Count_For_Supplier_Name
	lineageTag: bc4fbd49-ff20-48e1-8354-735bd22d54f1

	column Request_ID
		dataType: string
		lineageTag: ce4e511f-2101-4958-b7b0-56ea587cc561
		summarizeBy: none
		sourceColumn: Request_ID

		annotation SummarizationSetBy = Automatic

	column Supplier_KEY
		dataType: int64
		formatString: 0
		lineageTag: 5346a06d-4ef7-4fdb-a605-8722c9f9ca5b
		summarizeBy: sum
		sourceColumn: Supplier_KEY

		annotation SummarizationSetBy = Automatic

	column 'Candidates Submitted Count'
		dataType: double
		lineageTag: 00d47d26-a503-42b1-b62a-ea1b31e481a0
		summarizeBy: sum
		sourceColumn: Candidates Submitted Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FlowAux_Candidates_Submitted_Count_For_Supplier_Name = m
		mode: import
		source =
				let
				    Source = FlowPreFactRequestCandidate,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Request_ID", "Candidate_ID", "Supplier_KEY"}),
				    #"Grouped Rows" = Table.Group(#"Removed Other Columns", {"Request_ID", "Supplier_KEY"}, {{"Candidates Submitted Count", each List.Count([Candidate_ID]), type nullable number}})
				in
				    #"Grouped Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

