table FlowAux_Median_Submitted_Bill_Rates
	lineageTag: e17e5e61-4466-42f1-b52e-05702aec3060

	column Request_ID
		dataType: string
		lineageTag: 30e524c3-663f-4207-b68f-291ddb56610c
		summarizeBy: none
		sourceColumn: Request_ID

		annotation SummarizationSetBy = Automatic

	column 'Median Submitted Bill Rates'
		dataType: double
		lineageTag: ce14daeb-93d0-41fa-87c1-e20a18b86651
		summarizeBy: none
		sourceColumn: Median Submitted Bill Rates

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Median Submitted Bill Rates USD'
		dataType: double
		lineageTag: bc3f4041-5f80-4371-b1aa-3093afb1830b
		summarizeBy: none
		sourceColumn: Median Submitted Bill Rates USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FlowAux_Median_Submitted_Bill_Rates = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(),
				    Workspaces = Source{[Id = "Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId="8a87c474-d74a-479b-8616-3bbb0e4f223d"]}[Data],
				    Dataflow = Workspace{[dataflowId="22bc9ade-d2a9-44e0-bfe4-2f00ff94f2ed"]}[Data],
				    Entity = Dataflow{[entity="FlowAuxMergeRequestsCandidates"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Entity,{{"Candidate Offer Date", "Candidate Offer Extended Date"}, {"Candidate Qualified Date", "Candidate HM Qualified Date"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"Request_ID"}, FlowAux_Merge_Request_Dates_and_IDs, {"Request_ID"}, "FlowzzAuxMerge_Request_Dates_and_IDs", JoinKind.LeftOuter),
				    #"Expanded FlowzzAuxMerge_Request_Dates_and_IDs" = Table.ExpandTableColumn(#"Merged Queries", "FlowzzAuxMerge_Request_Dates_and_IDs", {"Request_ID", "Currency Exchange Rate to USD", "Rate Card Rate RT", "Request Filled Date", "Request Submitted Date", "Request Desired Start Date", "Procurement_Type_KEY", "Request Released Date", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}, {"Request_ID.1", "Currency Exchange Rate to USD", "Rate Card Rate RT", "Request Filled Date", "Request Submitted Date", "Request Desired Start Date", "Procurement_Type_KEY", "Request Released Date", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded FlowzzAuxMerge_Request_Dates_and_IDs", each [Request_ID.1] <> null),
				    NewColumnCandidateBillRateRTUSD = Table.AddColumn(#"Filtered Rows", "Candidate Bill Rate RT USD", each [Candidate Bill Rate RT] * [Currency Exchange Rate to USD], type number),
				    NewColumnCandidatePayRateRTUSD = Table.AddColumn(NewColumnCandidateBillRateRTUSD, "Candidate Pay Rate RT USD", each [Candidate Pay Rate RT] * [Currency Exchange Rate to USD], type number),
				    Median_Submitted_Bill_Rates = Table.Group(NewColumnCandidatePayRateRTUSD, {"Request_ID"}, {{"Median Submitted Bill Rates", each List.Median([Candidate Bill Rate RT]), type nullable number}, {"Median Submitted Bill Rates USD", each List.Median([Candidate Bill Rate RT USD]), type number}}),
				    #"Removed Duplicates" = Table.Distinct(Median_Submitted_Bill_Rates, {"Request_ID"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

