table FlowPreFactRequestsSupplier
	lineageTag: 7295a3c9-bb33-430f-8c69-099d55ad5b8b

	column 'Request ID'
		dataType: string
		lineageTag: b130f1e5-e96d-4436-bc49-a485f06349b6
		summarizeBy: none
		sourceColumn: Request ID

		annotation SummarizationSetBy = Automatic

	column 'Supplier Is Interested'
		dataType: string
		lineageTag: 18fd86be-dbaa-4fd4-9cf6-caaa2529bf35
		summarizeBy: none
		sourceColumn: Supplier Is Interested

		annotation SummarizationSetBy = Automatic

	column 'Supplier Release Status'
		dataType: string
		lineageTag: abcdafe9-fbf6-41c5-b4f4-60dc6f0406bc
		summarizeBy: none
		sourceColumn: Supplier Release Status

		annotation SummarizationSetBy = Automatic

	column 'Supplier Distribution Group'
		dataType: string
		lineageTag: 122df2a4-3fbc-49af-b090-12efd5a8f3d0
		summarizeBy: none
		sourceColumn: Supplier Distribution Group

		annotation SummarizationSetBy = Automatic

	column ClientNameInternal
		dataType: string
		lineageTag: 25258d53-cb41-48ac-ba5b-c18426a1fe22
		summarizeBy: none
		sourceColumn: ClientNameInternal

		annotation SummarizationSetBy = Automatic

	column Request_ID
		dataType: string
		lineageTag: af2f7cfc-b659-4524-840b-a79fb8aadd2b
		summarizeBy: none
		sourceColumn: Request_ID

		annotation SummarizationSetBy = Automatic

	column Client_Name_KEY
		dataType: int64
		formatString: 0
		lineageTag: c00e08f3-4776-4813-8043-f66b9c38792d
		summarizeBy: sum
		sourceColumn: Client_Name_KEY

		annotation SummarizationSetBy = Automatic

	column 'Supplier Released Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 41a3efad-21c9-424a-9a95-76900dbc5dbe
		summarizeBy: none
		sourceColumn: Supplier Released Date

		annotation SummarizationSetBy = Automatic

	column 'Data Refreshed Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: a782f071-78ad-43a2-b59c-a2d0615a8fc9
		summarizeBy: none
		sourceColumn: Data Refreshed Date

		annotation SummarizationSetBy = Automatic

	column Supplier_KEY
		dataType: int64
		formatString: 0
		lineageTag: c370ca0a-92c7-433d-a01e-784a834b9e33
		summarizeBy: sum
		sourceColumn: Supplier_KEY

		annotation SummarizationSetBy = Automatic

	column 'Currency Exchange Rate to USD'
		dataType: double
		lineageTag: f0ca091e-d53c-43b5-938b-7c00618a085f
		summarizeBy: sum
		sourceColumn: Currency Exchange Rate to USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Request Filled Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2bdbc55c-a7e8-494f-93b4-8653cebf1298
		summarizeBy: none
		sourceColumn: Request Filled Date

		annotation SummarizationSetBy = Automatic

	column Procurement_Type_KEY
		dataType: int64
		formatString: 0
		lineageTag: 3a1cbf2e-ef67-4930-b196-d12461d29cb6
		summarizeBy: sum
		sourceColumn: Procurement_Type_KEY

		annotation SummarizationSetBy = Automatic

	column Rate_Card_Category_1_KEY
		dataType: int64
		formatString: 0
		lineageTag: 34106a61-02bd-4aaa-baf9-7097aac4e102
		summarizeBy: sum
		sourceColumn: Rate_Card_Category_1_KEY

		annotation SummarizationSetBy = Automatic

	column 'Request Approved Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5d07c3aa-fe67-4030-8f0e-ecca6167c573
		summarizeBy: none
		sourceColumn: Request Approved Date

		annotation SummarizationSetBy = Automatic

	column Business_Unit_KEY
		dataType: int64
		formatString: 0
		lineageTag: 33e3ae6f-f49b-417e-94a5-c36ba19919a5
		summarizeBy: sum
		sourceColumn: Business_Unit_KEY

		annotation SummarizationSetBy = Automatic

	column Currency_KEY
		dataType: int64
		formatString: 0
		lineageTag: eef4153d-ea0d-444f-9f46-b62c83d5c48d
		summarizeBy: sum
		sourceColumn: Currency_KEY

		annotation SummarizationSetBy = Automatic

	column Work_Location_KEY
		dataType: int64
		formatString: 0
		lineageTag: 22f7ce8a-77d1-4175-830b-cad95a55e652
		summarizeBy: sum
		sourceColumn: Work_Location_KEY

		annotation SummarizationSetBy = Automatic

	column Job_Title_KEY
		dataType: int64
		formatString: 0
		lineageTag: 053ed371-9d7c-4cd8-81f7-2ea5b859bfdf
		summarizeBy: sum
		sourceColumn: Job_Title_KEY

		annotation SummarizationSetBy = Automatic

	column Rate_Card_Category_2_KEY
		dataType: int64
		formatString: 0
		lineageTag: cbe0869f-2aa6-4789-936f-d1efd8e90ff8
		summarizeBy: sum
		sourceColumn: Rate_Card_Category_2_KEY

		annotation SummarizationSetBy = Automatic

	column Labor_Category_KEY
		dataType: int64
		formatString: 0
		lineageTag: ca0f9a9c-a353-4ac9-8cd1-f80a58a1da3e
		summarizeBy: sum
		sourceColumn: Labor_Category_KEY

		annotation SummarizationSetBy = Automatic

	column Job_Class_KEY
		dataType: int64
		formatString: 0
		lineageTag: a891963b-d275-4877-a7fa-8b55d18bc30e
		summarizeBy: sum
		sourceColumn: Job_Class_KEY

		annotation SummarizationSetBy = Automatic

	column Hiring_Manager_KEY
		dataType: int64
		formatString: 0
		lineageTag: 78c0e616-4943-4ac0-802e-d901954474f9
		summarizeBy: sum
		sourceColumn: Hiring_Manager_KEY

		annotation SummarizationSetBy = Automatic

	column Cost_Center_KEY
		dataType: int64
		formatString: 0
		lineageTag: a9a7b418-7f2d-4d49-a068-3b21698463e5
		summarizeBy: sum
		sourceColumn: Cost_Center_KEY

		annotation SummarizationSetBy = Automatic

	column 'Candidates Submitted Count'
		dataType: double
		lineageTag: 2fd86b91-3a1b-43a6-9f73-d988a659a565
		summarizeBy: sum
		sourceColumn: Candidates Submitted Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Distribution Total Hours'
		dataType: double
		lineageTag: 3e218925-f3c0-45bb-9f85-6e40b4aab8fb
		summarizeBy: sum
		sourceColumn: Distribution Total Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Distribution Tier Category'
		dataType: string
		lineageTag: e572780d-6dc0-48f8-a409-53f46292230f
		summarizeBy: none
		sourceColumn: Distribution Tier Category

		annotation SummarizationSetBy = Automatic

	column 'Request Number of Openings'
		dataType: int64
		formatString: 0
		lineageTag: 5da2fddf-5f60-417d-b176-98fe25b913d2
		summarizeBy: sum
		sourceColumn: Request Number of Openings

		annotation SummarizationSetBy = Automatic

	partition FlowPreFactRequestsSupplier = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(),
				    Workspaces = Source{[Id = "Workspaces"]}[Data],
				    Workspace = Workspaces{[workspaceId="8a87c474-d74a-479b-8616-3bbb0e4f223d"]}[Data],
				    Dataflow = Workspace{[dataflowId="22bc9ade-d2a9-44e0-bfe4-2f00ff94f2ed"]}[Data],
				    Entity = Dataflow{[entity="FlowAuxRequestsSuppliers"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(Entity, {"Request_ID"}, FlowAux_Merge_Request_Dates_and_IDs, {"Request_ID"}, "FlowzzAuxMerge_Request_Dates_and_IDs", JoinKind.LeftOuter),
				    #"Expanded FlowzzAuxMerge_Request_Dates_and_IDs" = Table.ExpandTableColumn(#"Merged Queries", "FlowzzAuxMerge_Request_Dates_and_IDs", {"Currency Exchange Rate to USD", "Request Filled Date", "Procurement_Type_KEY", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}, {"Currency Exchange Rate to USD", "Request Filled Date", "Procurement_Type_KEY", "Rate_Card_Category_1_KEY", "Request Approved Date", "Business_Unit_KEY", "Currency_KEY", "Work_Location_KEY", "Job_Title_KEY", "Rate_Card_Category_2_KEY", "Labor_Category_KEY", "Job_Class_KEY", "Hiring_Manager_KEY", "Cost_Center_KEY"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded FlowzzAuxMerge_Request_Dates_and_IDs", {"Request_ID", "Supplier_KEY"}, FlowAux_Candidates_Submitted_Count_For_Supplier_Name, {"Request_ID", "Supplier_KEY"}, "FlowCandidates_Submitted_Count_For_Supplier_Name", JoinKind.LeftOuter),
				    #"Expanded FlowCandidates_Submitted_Count_For_Supplier_Name" = Table.ExpandTableColumn(#"Merged Queries1", "FlowCandidates_Submitted_Count_For_Supplier_Name", {"Candidates Submitted Count"}, {"Candidates Submitted Count"}),
				    NewColumnDistributionTotalHours = Table.AddColumn(#"Expanded FlowCandidates_Submitted_Count_For_Supplier_Name", "Distribution Total Hours", each Duration.TotalHours([Supplier Released Date] - [Request Approved Date]), type number),
				    NewColumnDistributionTierCategory = Table.AddColumn(NewColumnDistributionTotalHours, "Distribution Tier Category", each if [Distribution Total Hours] = null then "(NULL)" else if [Distribution Total Hours] < 0 then "Backdated" else if [Distribution Total Hours] <= 24 then "0 - 24 hrs" else if [Distribution Total Hours] <= 48 then "24 - 48 hrs" else "48+ hrs", type text),
				    #"Merged Queries2" = Table.NestedJoin(NewColumnDistributionTierCategory, {"Request_ID"}, FlowAux_PreFactRequest, {"Request_ID"}, "FlowAux_PreFactRequest", JoinKind.LeftOuter),
				    #"Expanded FlowAux_PreFactRequest" = Table.ExpandTableColumn(#"Merged Queries2", "FlowAux_PreFactRequest", {"Request Number of Openings"}, {"Request Number of Openings"}),
				    RemovedDuplicatesKEYTable = Table.Distinct(#"Expanded FlowAux_PreFactRequest", {"Request_ID", "Supplier_KEY"})
				in
				    RemovedDuplicatesKEYTable

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

