/// For FlowPrefactRequestSupplier
table FlowAux_PreFactRequest
	lineageTag: 76993efd-d306-4964-a85f-438eabff7106

	column Request_ID
		dataType: string
		lineageTag: b9e509ce-5752-43b4-9cd2-2d6c762a6527
		summarizeBy: none
		sourceColumn: Request_ID

		annotation SummarizationSetBy = Automatic

	column 'Request Number of Openings'
		dataType: int64
		formatString: 0
		lineageTag: 79bab02d-3f9f-43bf-a9d0-194f8d8d1d29
		summarizeBy: none
		sourceColumn: Request Number of Openings

		annotation SummarizationSetBy = Automatic

	partition FlowAux_PreFactRequest = m
		mode: import
		source =
				let
				    Source = FlowPreFactRequest,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Request_ID", "Request Number of Openings"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Request_ID"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

